/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inicio;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import modelo.F1;
import modelo.conexion;

/**
 *
 * @author Josue
 */
public class empleados extends javax.swing.JPanel {

    /**
     * Creates new form empleados
     */
    
    F1 ejecutar = new F1();
       
    public empleados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jDayChooser1 = new com.toedter.calendar.JDayChooser();
        jDayChooser2 = new com.toedter.calendar.JDayChooser();
        jLabel1 = new javax.swing.JLabel();
        jCBRol = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTFSalario = new javax.swing.JTextField();
        jTFNombre = new javax.swing.JTextField();
        jTFApellido = new javax.swing.JTextField();
        jTFTelefono = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jDCFechaNacimiento = new com.toedter.calendar.JDateChooser();
        jCBContrato = new javax.swing.JComboBox<>();

        jScrollPane1.setViewportView(jTree1);

        setBackground(new java.awt.Color(153, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("INGRESE TIPO DE EMPLEADO");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 83, -1, -1));

        jCBRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "DOCTOR", "ENFERMERIA", "ADMINISTRACION", "SEGURIDAD", "MANTENIMIENTO" }));
        add(jCBRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 78, 170, -1));

        jLabel3.setText("  NOMBRE");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        jLabel4.setText("APELLIDO");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));

        jLabel5.setText("TELEFONO");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        jLabel6.setText("CONTRATO");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        jLabel7.setText("FECHA DE NACIMIENTO");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        jLabel8.setText(" SALARIO");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, -1, -1));
        add(jTFSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 170, -1));

        jTFNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFNombreFocusLost(evt);
            }
        });
        jTFNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNombreActionPerformed(evt);
            }
        });
        add(jTFNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 170, -1));
        add(jTFApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 170, -1));
        add(jTFTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 170, -1));

        jLabel9.setFont(new java.awt.Font("Castellar", 0, 24)); // NOI18N
        jLabel9.setText("INGRESO DE DATOS EMPLEADOS");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 30, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/Accept_37154 (1).png"))); // NOI18N
        jButton1.setText("ACEPTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/cancelar.png"))); // NOI18N
        jButton2.setText("CANCELAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/programador (1).png"))); // NOI18N
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 134, -1, -1));
        add(jDCFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 170, -1));

        jCBContrato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "SI", "NO" }));
        add(jCBContrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 170, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if(guardar()){
        
            resetDatos();
        }
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
         resetDatos();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTFNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFNombreFocusLost
    }//GEN-LAST:event_jTFNombreFocusLost

    private void jTFNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNombreActionPerformed

    public void resetDatos(){
    
        jTFNombre.setText("");
        jTFApellido.setText("");
        jTFTelefono.setText("");
        jCBContrato.setSelectedIndex(0);
        jDCFechaNacimiento.setCalendar(null);
        jTFSalario.setText("");
        
        
        
    }
    
    public boolean guardar(){
    
        String nombre = jTFNombre.getText();
        String apellido = jTFApellido.getText();
        String telefono = jTFTelefono.getText();
        double salario = Double.parseDouble(jTFSalario.getText());
        String fecha = ((JTextField) jDCFechaNacimiento.getDateEditor().getUiComponent()).getText();
        String contratado = (String) jCBContrato.getSelectedItem();
        String rol = (String) jCBRol.getSelectedItem();
        
        int contrato=0;
        
        if(contratado.equals("SI")){
            contrato = 1;
        
        }else if (contratado.equals("NO")){
        
            contrato = 0;
        }
        
        
        
       String query = "INSERT INTO empleados(nombreEmpleado,apellidoEmpleado,telefono,fechaNacimiento,salario,contrato,rol)"
                   + "VALUES ('"+nombre+"','"+apellido+"','"+telefono+"','"+fecha+"','"+salario+"','"+contrato+"','"+rol+"')";
       


       return ejecutar.ejecutarQuery(query);
        
        
    
    }
    
  
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jCBContrato;
    private javax.swing.JComboBox<String> jCBRol;
    private com.toedter.calendar.JDateChooser jDCFechaNacimiento;
    private com.toedter.calendar.JDayChooser jDayChooser1;
    private com.toedter.calendar.JDayChooser jDayChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFApellido;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFSalario;
    private javax.swing.JTextField jTFTelefono;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
