/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inicio;

import javax.swing.JTextField;
import modelo.F1;

/**
 *
 * @author Josue
 */
public class farmacia extends javax.swing.JPanel {

    /**
     * Creates new form farmacia
     */
    
    F1 ejecutar = new F1();
       
    public farmacia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTFNombre = new javax.swing.JTextField();
        jTFMarca = new javax.swing.JTextField();
        jTFPrecioCosto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jDCVencimiento = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        JTFExistencia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTFPrecioVenta = new javax.swing.JTextField();

        jLabel5.setText("jLabel5");

        setBackground(new java.awt.Color(153, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Castellar", 0, 30)); // NOI18N
        jLabel9.setText("INGRESO DE DATOS MEDICAMENTOS");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 28, -1, -1));

        jLabel2.setText("NOMBRE");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        jLabel3.setText("VENCIMIENTO");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        jLabel4.setText("MARCA");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        jLabel6.setText("PRECIO COSTO");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));
        add(jTFNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 130, -1));
        add(jTFMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 130, -1));

        jTFPrecioCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFPrecioCostoActionPerformed(evt);
            }
        });
        add(jTFPrecioCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 130, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/capsule_drug_medicine_pill_tablet_icon_140097.png"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 108, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/cancelar.png"))); // NOI18N
        jButton2.setText("CANCELAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/Accept_37154 (1).png"))); // NOI18N
        jButton1.setText("ACEPTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, -1, -1));
        add(jDCVencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 130, -1));

        jLabel1.setText("Existencia");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));
        add(JTFExistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 130, -1));

        jLabel8.setText("PRECIO VENTA");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));
        add(jTFPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 130, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jTFPrecioCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFPrecioCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFPrecioCostoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(guardar()){
        
            resetDatos();
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        resetDatos();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    
    public void resetDatos(){
    
        jTFNombre.setText("");
        jDCVencimiento.setCalendar(null);
        jTFMarca.setText("");
        jTFPrecioCosto.setText("");
        jTFPrecioVenta.setText("");
        JTFExistencia.setText("");
    
    
    }
    
    public boolean guardar(){
    
        String nombre = jTFNombre.getText();
        String fecha = ((JTextField) jDCVencimiento.getDateEditor().getUiComponent()).getText();
        String marca = jTFMarca.getText();
        double precioCosto = Double.parseDouble(jTFPrecioCosto.getText());
        double precioVenta = Double.parseDouble(jTFPrecioVenta.getText());
        int existencia = Integer.parseInt(JTFExistencia.getText());
        
        String guery = "INSERT INTO articulosFarmacia(nombre,marca,precioCosto,vencimiento,precioVenta,existencia)"
                + "VALUES ('"+nombre+"','"+marca+"','"+precioCosto+"','"+fecha+"','"+precioVenta+"','"+existencia+"')";
        
        return ejecutar.ejecutarQuery(guery);
        
    
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTFExistencia;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDCVencimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTFMarca;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFPrecioCosto;
    private javax.swing.JTextField jTFPrecioVenta;
    // End of variables declaration//GEN-END:variables
}
