/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inicio;

import javax.swing.JTextField;
import modelo.F1;

/**
 *
 * @author Josue
 */
public class paciente extends javax.swing.JPanel {

    /**
     * Creates new form paciente
     */
    
    F1 ejecutar = new F1();
    
    public paciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTFNombre = new javax.swing.JTextField();
        jTFApellido = new javax.swing.JTextField();
        jTFTelefono = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jDCFechaNacimiento = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        JDCFechaIngreso = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(153, 255, 204));
        setToolTipText("");
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Castellar", 0, 36)); // NOI18N
        jLabel9.setText("INGRESO DE DATOS PACIENTE");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 40, -1, -1));

        jLabel2.setText("NOMBRE");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        jLabel3.setText("APELLIDO");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        jLabel4.setText("TELEFONO");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        jLabel5.setText("FECHA DE NACIMIENTO");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));
        add(jTFNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 140, -1));
        add(jTFApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 140, -1));
        add(jTFTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 140, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/Accept_37154 (1).png"))); // NOI18N
        jButton1.setText("ACEPTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 409, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/cancelar.png"))); // NOI18N
        jButton2.setText("CANCELAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 409, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/paciente.png"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 122, -1, -1));
        add(jDCFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 140, -1));

        jLabel1.setText("FECHA DE INGRESO");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));
        add(JDCFechaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 140, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if(guardar()){
        
            resetDatos();
        
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        resetDatos();
    }//GEN-LAST:event_jButton2ActionPerformed

    public void resetDatos(){
        
        jTFNombre.setText("");
        jTFApellido.setText("");
        jTFTelefono.setText("");
        jDCFechaNacimiento.setCalendar(null);
        JDCFechaIngreso.setCalendar(null);
        
    
    }

    public boolean guardar (){
    
            
        String nombre = jTFNombre.getText();
        String apellido = jTFApellido.getText();
        String telefono = jTFTelefono.getText();
        String fechaNacimiento = ((JTextField) jDCFechaNacimiento.getDateEditor().getUiComponent()).getText();
        String fechaIngreso = ((JTextField) JDCFechaIngreso.getDateEditor().getUiComponent()).getText();
        
        String query = "INSERT INTO paciente(nombrePaciente,apellidoPaciente,telefonoPaciente,fechaNacimiento,fechaIngreso)"
                + "VALUES('"+nombre+"','"+apellido+"','"+telefono+"','"+fechaNacimiento+"','"+fechaIngreso+"')";
        
        
        return ejecutar.ejecutarQuery(query);
    
    
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JDCFechaIngreso;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDCFechaNacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTFApellido;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFTelefono;
    // End of variables declaration//GEN-END:variables
}
