/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inicio;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import modelo.F1;

/**
 *
 * @author Josue
 */
public class ventas extends javax.swing.JPanel {

    /**
     * Creates new form ventas
     */
    
    
     F1 con = new F1();
    DefaultTableModel tablaArticulos = new DefaultTableModel();
   // double precio=0;
    
  
    public ventas() {
        
        initComponents();
        mostrarArticulos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTFPrecio = new javax.swing.JTextField();
        jTFTotal = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSCantidad = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTArticulos = new javax.swing.JTable();

        jScrollPane1.setViewportView(jEditorPane1);

        setBackground(new java.awt.Color(153, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("CANTIDAD DE ARTICULO");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 211, -1, -1));

        jLabel4.setText("PRECIO");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 255, -1, -1));

        jLabel5.setText("TOTAL");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 299, -1, -1));

        jLabel9.setFont(new java.awt.Font("Castellar", 0, 36)); // NOI18N
        jLabel9.setText("INGRESO DE VENTAS");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 30, -1, -1));

        jTFPrecio.setEditable(false);
        add(jTFPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 130, -1));

        jTFTotal.setEditable(false);
        add(jTFTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 130, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/cancelar.png"))); // NOI18N
        jButton2.setText("CANCELAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 367, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/Accept_37154 (1).png"))); // NOI18N
        jButton1.setText("ACEPTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 367, -1, -1));
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(732, 226, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/ventas.png"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, -1, -1));

        jSCantidad.setModel(new javax.swing.SpinnerNumberModel());
        jSCantidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSCantidadStateChanged(evt);
            }
        });
        jSCantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jSCantidadFocusGained(evt);
            }
        });
        jSCantidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSCantidadMouseClicked(evt);
            }
        });
        add(jSCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 60, -1));

        jLabel8.setText("SELECCIONE UN ARTICULO:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        jTArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTArticulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTArticulosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTArticulos);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 370, 100));
    }// </editor-fold>//GEN-END:initComponents

    private void jSCantidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSCantidadMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jSCantidadMouseClicked

    private void jSCantidadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jSCantidadFocusGained
        // TODO add your handling code here:
        
     
    }//GEN-LAST:event_jSCantidadFocusGained

    private void jSCantidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSCantidadStateChanged
        // TODO add your handling code here:
        
   
        int cantidad = (Integer) jSCantidad.getValue();
        double precioV = Double.parseDouble(jTFPrecio.getText());
        double total = Math.round((cantidad*precioV)*100d)/100d;
        
        String total2 = Double.toString(total);
        jTFTotal.setText(total2);
       
       
    }//GEN-LAST:event_jSCantidadStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        guardarEnBase();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTFPrecio.setText("");
        jTFTotal.setText("");
     //   jSCantidad.set
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTArticulosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTArticulosMouseClicked
        // TODO add your handling code here:
        
        mostrarPrecio();
    }//GEN-LAST:event_jTArticulosMouseClicked

    
    public void mostrarPrecio(){
    
         DefaultTableModel modeloArticulo = (DefaultTableModel) jTArticulos.getModel();

         String precioVS;
         precioVS = Double.toString((Double)modeloArticulo.getValueAt(jTArticulos.getSelectedRow(), 2) );
        
         jTFPrecio.setText(precioVS);
              
    }
    
      
 
    public void guardarEnBase(){
    
        DefaultTableModel modeloArticulo = (DefaultTableModel) jTArticulos.getModel();
        
         String idProducto;
         idProducto = Integer.toString((Integer)modeloArticulo.getValueAt(jTArticulos.getSelectedRow(), 0) );
         int idProduc = Integer.parseInt(idProducto);
         int cantidad = (Integer) jSCantidad.getValue();
         double precio = Double.parseDouble(jTFPrecio.getText());
         double total = Double.parseDouble(jTFTotal.getText());
         
         String query = "INSERT INTO factura(cantidad,precio,total,articulosFarmacia_idArticulo)"
                 + "VALUES('"+cantidad+"','"+precio+"','"+total+"','"+idProduc+"')";
         
         con.ejecutarQuery(query);
         
         
    
    }
    
    public void mostrarArticulos(){
    
        
        jTArticulos.setModel(tablaArticulos);
          
        tablaArticulos.setColumnIdentifiers(new Object[] {"CODIGO","NOMBRE","PRECIO","EXISTENCIA"});
        
        String query = "SELECT * FROM articulosfarmacia";
        ResultSet resultado = con.ejecutarQuery2(query);
        
        try{
        
            while (resultado.next()){
                
                                       
                tablaArticulos.addRow(new Object[] {resultado.getInt("idArticulo"),resultado.getString("nombre"),+resultado.getDouble("precioVenta"),resultado.getInt("existencia")});
               // precio =resultado.getDouble("precioVenta");
            
           }
        
        }catch(SQLException ex){
            
            
            System.out.println(ex.toString());
        }

      
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner jSCantidad;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTArticulos;
    private javax.swing.JTextField jTFPrecio;
    private javax.swing.JTextField jTFTotal;
    // End of variables declaration//GEN-END:variables

 
}
