/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inicio;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import modelo.F1;

/**
 *
 * @author Josue
 */
public class visor extends javax.swing.JPanel {

    /**
     * Creates new form visor
     */
    
    F1 con = new F1();
    DefaultTableModel tablaCitas = new DefaultTableModel();
    
    
    public visor() {
        initComponents();
        
        mostrarCitas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTCitas = new javax.swing.JTable();

        setBackground(new java.awt.Color(153, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("LISTADO DE CITAS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        jTCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTCitas);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 640, 330));
    }// </editor-fold>//GEN-END:initComponents


    public void mostrarCitas(){
        
        ResultSet resultado;
        
        jTCitas.setModel(tablaCitas);
        
        tablaCitas.setColumnIdentifiers(new Object[] {"CODIGO","HORA","FECHA","DOCTOR","PACIENTE","DIAGNOSTICO"});
        
        String query ="SELECT * FROM citas";
        
        resultado = con.ejecutarQuery2(query);
        
        
        
        try{
        
            while (resultado.next()){
                
                                       
                tablaCitas.addRow(new Object[] {resultado.getInt("idCita"),resultado.getString("horaCita"),resultado.getString("diaCita"),resultado.getInt("empleados_idEmpleado"),
                resultado.getInt("empleados_idEmpleado"),resultado.getString("diagnostico")});
            
           }
        
        }catch(SQLException ex){
            
            
            System.out.println(ex.toString());
        }
        
        
        
    
    
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTCitas;
    // End of variables declaration//GEN-END:variables
}
